version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 122edoragl
      POSTGRES_DB: autocar_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
